name: Build and Test

# Workflow is triggered only on push to the master branch or a pull request to
# the master branch

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # Run job for both python versions in the docker image
    container:
      image: hoffmanlab/genomedata-test:latest

    steps:
      - uses: actions/checkout@v2
      - name: Install test dependencies
        run: |
          pip install flake8 mypy types-six types-pkg_resources
      - name: Lint with flake8
        run: |
          flake8 . --exclude 'doc/conf.py examples/*' --count --statistics
      - name: Type check with mypy
        run: |
          mypy genomedata test
      - name: Build repository
        run: |
          python3 -m build
      - name: Install from source
        run: |
          python3 -m pip install .
          pip list
      - name: Run tests
        run: |
          cd test && python3 run_tests.py
